---
title: "dplyr"
subtitle: "Data Transformations"
author: "‽"
date: "`r Sys.Date()`"
output: html_notebook
---

# dplyr

- filter  (rows)
- arrange (sort rows by variables)
- select (columns)
- mutate (change cell values)
- Count
- Summarize

```{r}
library(dplyr)
```


###### http://r4ds.had.co.nz/transform.html#introduction-2
###### http://dplyr.tidyverse.org/

```{r}
starwars
```

## Filter

```{r}
#starwars_small <- starwars %>% 
#  filter(!is.na(mass), !is.na(height))
starwars_small <- starwars %>% 
  filter(mass >= 0)
```

## Arrange

```{r}
starwars_small %>% 
  arrange(desc(height), desc(name))
```

## Select

```{r}
starwars_small %>% 
  arrange(species, height) %>% 
  select(name, species, height, mass, birth_year)
```


```{r}
starwars_small %>% 
  select(name, species, height, mass, birth_year) %>% 
  arrange(species, desc(height), mass, name) %>% 
  filter(species == "Human") 
  
```



## Mutate

```{r}
starwars_small %>% 
  select(name, species, height, mass, birth_year) %>% 
  arrange(species, desc(height), mass, name) %>% 
  filter(species == "Human") %>% 
  mutate(BMI = round(height / mass, 2))
```


## Count

```{r}
starwars %>% 
  count(mass) %>% 
  drop_na() %>% 
  arrange(desc(n))
```


## Summarize

```{r}
starwars %>% 
  filter(!is.na(height)) %>% 
  group_by(species) %>% 
  summarise(Count = n(), mean_ht = mean(height), min_ht = min(height),
            max_ht = max(height), sum_ht = sum(height)) %>% 
  arrange(desc(Count))
```


# More information

https://rfun.library.duke.edu/intro2r